spring:
  config:
    import: optional:configserver:http://localhost:8888  # Commenter ou supprimer si non utilisé
  application:
    name: passager-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: passager
      authentication-database: admin
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "http://localhost:9098/realms/JobBoardKeycloack"
server:
  port: 8091

# Configuration Twilio (optionnelle)
twilio:
  account:
    sid: ACe6dbad8422395de0446be738c7155d49
  auth:
    token: 8533bd52b0a9aff02c1b64660389aa7e
  phone:
    number: +16893198559

