spring:
  config:
    import: optional:configserver:http://localhost:8888  # Commenter ou supprimer si non utilisé
  application:
    name: passager-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: passager
      authentication-database: admin

server:
  port: 8091

