spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: LivraisonBagages-service

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "http://localhost:9098/realms/JobBoardKeycloack"

server:
  port: 8093




