server:
  port: 8086

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:AgentAeroport
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  debug: true
